version: "3.1"

services:

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${dbUser}
      MONGO_INITDB_ROOT_PASSWORD: ${dbPass}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${port}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${dbUser}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${dbPass}
      ME_CONFIG_MONGODB_URL: ${mongoURI}