name: pull-request-build

on:
  pull_request:
    branches:
       - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Create .env File
        run: |
          echo "DB_URI=true" >> .env
          echo "DB_NAME=true" >> .env
          echo "DB_COLL=true" >> .env
          echo "API_KEY=true" >> .env
      - name: Build Docker image
        run: docker build . --file Dockerfile